---
apiVersion: v2
name: actions-runner
description: Deploy GitHub Actions self-hosted runner
type: application
version: 2.330.0-6
appVersion: 2.330.0-6
icon: https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Ministry_of_Justice_logo_%28United_Kingdom%29.svg/611px-Ministry_of_Justice_logo_%28United_Kingdom%29.svg.png
maintainers:
  - name: moj-data-platform-robot
    email: analytical-platform@digital.justice.gov.uk
